### ISSUE TITLE
simpleserver.py has inconsistent indentation on Windows

### ISSUE THREAD

**Issue by thekenu** [karthikp-ubc/CPEN400A-codesamples#2]
The below code snippet doesn't have consistent use of tabs and spaces. Try highlighting the leading white spaces on line 25 and 26.
https://github.com/karthikp-ubc/CPEN400A-codesamples/blob/c4dab054143c19ac1c29e1eab41909684eb60a95/lecture6/server/simpleserver.py#L23-L47

It renders incorrectly on Windows with Tab size: 4 spaces
![image](https://user-images.githubusercontent.com/16970019/47385918-3bcaa000-d6c0-11e8-8bc2-9707a5cbf5ca.png)

When run on the terminal, it throws the exception: 
```
  File "C:\...\CPEN 400A\CPEN400A-codesamples\lecture6\server\simpleserver.py", line 27
    success = True
                 ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by karthikp-ubc** [comment]
Sorry, but I don't have a Windows machine to test this on. If you or someone else can submit a patch, I'll accept it, but I can't fix the bug myself.
